/* Generated By:JavaCC: Do not edit this line. CALLanguageTreeConstants.java Version 5.0 */
public interface CALLanguageTreeConstants
{
  public int JJTPROG = 0;
  public int JJTVOID = 1;
  public int JJTVARDECL = 2;
  public int JJTCONSTDECL = 3;
  public int JJTCONSTASSIGN = 4;
  public int JJTFUNC = 5;
  public int JJTFUNCRET = 6;
  public int JJTPARAMLIST = 7;
  public int JJTNEMPPARAMLIST = 8;
  public int JJTMAIN = 9;
  public int JJTASSIGN = 10;
  public int JJTELSE = 11;
  public int JJTIF = 12;
  public int JJTWHILE = 13;
  public int JJTPLUSOP = 14;
  public int JJTMINOP = 15;
  public int JJTNUM = 16;
  public int JJTBOOL = 17;
  public int JJTOROP = 18;
  public int JJTANDOP = 19;
  public int JJTEQOP = 20;
  public int JJTNOTOP = 21;
  public int JJTLTOP = 22;
  public int JJTLTEQOP = 23;
  public int JJTGTOP = 24;
  public int JJTGTEQOP = 25;
  public int JJTARGLIST = 26;
  public int JJTIDENTIFIER = 27;
  public int JJTTYPE = 28;


  public String[] jjtNodeName = {
    "Prog",
    "void",
    "VarDecl",
    "ConstDecl",
    "ConstAssign",
    "Func",
    "FuncRet",
    "ParamList",
    "NempParamList",
    "Main",
    "Assign",
    "Else",
    "If",
    "While",
    "PlusOp",
    "MinOp",
    "Num",
    "Bool",
    "OrOp",
    "AndOp",
    "EqOp",
    "NotOp",
    "LtOp",
    "LtEqOp",
    "GtOp",
    "GtEqOp",
    "ArgList",
    "identifier",
    "type",
  };
}
/* JavaCC - OriginalChecksum=f3da9f362867b1ed2775448376b93842 (do not edit this line) */
