/* Generated By:JJTree&JavaCC: Do not edit this line. CALLanguageConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CALLanguageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VARIABLE = 11;
  /** RegularExpression Id. */
  int CONSTANT = 12;
  /** RegularExpression Id. */
  int RETURN = 13;
  /** RegularExpression Id. */
  int INTEGER = 14;
  /** RegularExpression Id. */
  int BOOLEAN = 15;
  /** RegularExpression Id. */
  int VOID = 16;
  /** RegularExpression Id. */
  int MAIN = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int SKP = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int BEGIN = 24;
  /** RegularExpression Id. */
  int END = 25;
  /** RegularExpression Id. */
  int IS = 26;
  /** RegularExpression Id. */
  int SEMI_COLON = 27;
  /** RegularExpression Id. */
  int COMMA = 28;
  /** RegularExpression Id. */
  int COLON = 29;
  /** RegularExpression Id. */
  int ASSIGNMENT = 30;
  /** RegularExpression Id. */
  int LBR = 31;
  /** RegularExpression Id. */
  int RBR = 32;
  /** RegularExpression Id. */
  int PLUS_SIGN = 33;
  /** RegularExpression Id. */
  int MINUS_SIGN = 34;
  /** RegularExpression Id. */
  int NEGATION = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int AND = 37;
  /** RegularExpression Id. */
  int EQUALS = 38;
  /** RegularExpression Id. */
  int NOT_EQUALS = 39;
  /** RegularExpression Id. */
  int LESS_THEN = 40;
  /** RegularExpression Id. */
  int GRT_THEN = 41;
  /** RegularExpression Id. */
  int LESS_EQUAL = 42;
  /** RegularExpression Id. */
  int GRT_EQUAL = 43;
  /** RegularExpression Id. */
  int INTEGERS = 44;
  /** RegularExpression Id. */
  int DIGITS = 45;
  /** RegularExpression Id. */
  int NEGATIVE_DIGITS = 46;
  /** RegularExpression Id. */
  int IDENTIFIER = 47;
  /** RegularExpression Id. */
  int LETTER = 48;
  /** RegularExpression Id. */
  int OTHER = 49;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "\"variable\"",
    "\"constant\"",
    "\"return\"",
    "\"integer\"",
    "\"boolean\"",
    "\"void\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"skip\"",
    "\"false\"",
    "\"while\"",
    "\"begin\"",
    "\"end\"",
    "\"is\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"~\"",
    "\"|\"",
    "\"&\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "<INTEGERS>",
    "<DIGITS>",
    "<NEGATIVE_DIGITS>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<OTHER>",
  };

}
