/* Generated By:JJTree: Do not edit this line. PlusOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class PlusOp extends SimpleNode {
  public PlusOp(int id) {
    super(id);
  }

  public PlusOp(CALLanguage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CALLanguageVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f3cbe567d6c9c78047273b220a5b171e (do not edit this line) */
